# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArenaMapExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArenaMapExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArenaMapExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArenaMapExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArenaMapExcel
    def UniqueId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ArenaMapExcel
    def TerrainType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ArenaMapExcel
    def TerrainTypeLocalizeKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ArenaMapExcel
    def ImagePath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ArenaMapExcel
    def GroundGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ArenaMapExcel
    def GroundGroupNameLocalizeKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ArenaMapExcel
    def StartRank(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ArenaMapExcel
    def EndRank(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ArenaMapExcel
    def GroundId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(9)
def ArenaMapExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddUniqueId(builder, UniqueId): builder.PrependInt64Slot(0, UniqueId, 0)
def ArenaMapExcelAddUniqueId(builder, UniqueId):
    """This method is deprecated. Please switch to AddUniqueId."""
    return AddUniqueId(builder, UniqueId)
def AddTerrainType(builder, TerrainType): builder.PrependInt64Slot(1, TerrainType, 0)
def ArenaMapExcelAddTerrainType(builder, TerrainType):
    """This method is deprecated. Please switch to AddTerrainType."""
    return AddTerrainType(builder, TerrainType)
def AddTerrainTypeLocalizeKey(builder, TerrainTypeLocalizeKey): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(TerrainTypeLocalizeKey), 0)
def ArenaMapExcelAddTerrainTypeLocalizeKey(builder, TerrainTypeLocalizeKey):
    """This method is deprecated. Please switch to AddTerrainTypeLocalizeKey."""
    return AddTerrainTypeLocalizeKey(builder, TerrainTypeLocalizeKey)
def AddImagePath(builder, ImagePath): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ImagePath), 0)
def ArenaMapExcelAddImagePath(builder, ImagePath):
    """This method is deprecated. Please switch to AddImagePath."""
    return AddImagePath(builder, ImagePath)
def AddGroundGroupId(builder, GroundGroupId): builder.PrependInt64Slot(4, GroundGroupId, 0)
def ArenaMapExcelAddGroundGroupId(builder, GroundGroupId):
    """This method is deprecated. Please switch to AddGroundGroupId."""
    return AddGroundGroupId(builder, GroundGroupId)
def AddGroundGroupNameLocalizeKey(builder, GroundGroupNameLocalizeKey): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(GroundGroupNameLocalizeKey), 0)
def ArenaMapExcelAddGroundGroupNameLocalizeKey(builder, GroundGroupNameLocalizeKey):
    """This method is deprecated. Please switch to AddGroundGroupNameLocalizeKey."""
    return AddGroundGroupNameLocalizeKey(builder, GroundGroupNameLocalizeKey)
def AddStartRank(builder, StartRank): builder.PrependInt64Slot(6, StartRank, 0)
def ArenaMapExcelAddStartRank(builder, StartRank):
    """This method is deprecated. Please switch to AddStartRank."""
    return AddStartRank(builder, StartRank)
def AddEndRank(builder, EndRank): builder.PrependInt64Slot(7, EndRank, 0)
def ArenaMapExcelAddEndRank(builder, EndRank):
    """This method is deprecated. Please switch to AddEndRank."""
    return AddEndRank(builder, EndRank)
def AddGroundId(builder, GroundId): builder.PrependInt64Slot(8, GroundId, 0)
def ArenaMapExcelAddGroundId(builder, GroundId):
    """This method is deprecated. Please switch to AddGroundId."""
    return AddGroundId(builder, GroundId)
def End(builder): return builder.EndObject()
def ArenaMapExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)