# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AudioAnimatorExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AudioAnimatorExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAudioAnimatorExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AudioAnimatorExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AudioAnimatorExcel
    def ControllerNameHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AudioAnimatorExcel
    def VoiceNamePrefix(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AudioAnimatorExcel
    def StateNameHash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AudioAnimatorExcel
    def StateName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # AudioAnimatorExcel
    def IgnoreInterruptDelay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # AudioAnimatorExcel
    def IgnoreInterruptPlay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # AudioAnimatorExcel
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AudioAnimatorExcel
    def Delay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # AudioAnimatorExcel
    def AudioPriority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # AudioAnimatorExcel
    def AudioClipPath(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # AudioAnimatorExcel
    def AudioClipPathLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AudioAnimatorExcel
    def AudioClipPathIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        return o == 0

    # AudioAnimatorExcel
    def VoiceHash(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # AudioAnimatorExcel
    def VoiceHashAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint32Flags, o)
        return 0

    # AudioAnimatorExcel
    def VoiceHashLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # AudioAnimatorExcel
    def VoiceHashIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        return o == 0

def Start(builder): builder.StartObject(11)
def AudioAnimatorExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddControllerNameHash(builder, ControllerNameHash): builder.PrependUint32Slot(0, ControllerNameHash, 0)
def AudioAnimatorExcelAddControllerNameHash(builder, ControllerNameHash):
    """This method is deprecated. Please switch to AddControllerNameHash."""
    return AddControllerNameHash(builder, ControllerNameHash)
def AddVoiceNamePrefix(builder, VoiceNamePrefix): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(VoiceNamePrefix), 0)
def AudioAnimatorExcelAddVoiceNamePrefix(builder, VoiceNamePrefix):
    """This method is deprecated. Please switch to AddVoiceNamePrefix."""
    return AddVoiceNamePrefix(builder, VoiceNamePrefix)
def AddStateNameHash(builder, StateNameHash): builder.PrependUint32Slot(2, StateNameHash, 0)
def AudioAnimatorExcelAddStateNameHash(builder, StateNameHash):
    """This method is deprecated. Please switch to AddStateNameHash."""
    return AddStateNameHash(builder, StateNameHash)
def AddStateName(builder, StateName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(StateName), 0)
def AudioAnimatorExcelAddStateName(builder, StateName):
    """This method is deprecated. Please switch to AddStateName."""
    return AddStateName(builder, StateName)
def AddIgnoreInterruptDelay(builder, IgnoreInterruptDelay): builder.PrependBoolSlot(4, IgnoreInterruptDelay, 0)
def AudioAnimatorExcelAddIgnoreInterruptDelay(builder, IgnoreInterruptDelay):
    """This method is deprecated. Please switch to AddIgnoreInterruptDelay."""
    return AddIgnoreInterruptDelay(builder, IgnoreInterruptDelay)
def AddIgnoreInterruptPlay(builder, IgnoreInterruptPlay): builder.PrependBoolSlot(5, IgnoreInterruptPlay, 0)
def AudioAnimatorExcelAddIgnoreInterruptPlay(builder, IgnoreInterruptPlay):
    """This method is deprecated. Please switch to AddIgnoreInterruptPlay."""
    return AddIgnoreInterruptPlay(builder, IgnoreInterruptPlay)
def AddVolume(builder, Volume): builder.PrependFloat32Slot(6, Volume, 0.0)
def AudioAnimatorExcelAddVolume(builder, Volume):
    """This method is deprecated. Please switch to AddVolume."""
    return AddVolume(builder, Volume)
def AddDelay(builder, Delay): builder.PrependFloat32Slot(7, Delay, 0.0)
def AudioAnimatorExcelAddDelay(builder, Delay):
    """This method is deprecated. Please switch to AddDelay."""
    return AddDelay(builder, Delay)
def AddAudioPriority(builder, AudioPriority): builder.PrependInt32Slot(8, AudioPriority, 0)
def AudioAnimatorExcelAddAudioPriority(builder, AudioPriority):
    """This method is deprecated. Please switch to AddAudioPriority."""
    return AddAudioPriority(builder, AudioPriority)
def AddAudioClipPath(builder, AudioClipPath): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(AudioClipPath), 0)
def AudioAnimatorExcelAddAudioClipPath(builder, AudioClipPath):
    """This method is deprecated. Please switch to AddAudioClipPath."""
    return AddAudioClipPath(builder, AudioClipPath)
def StartAudioClipPathVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AudioAnimatorExcelStartAudioClipPathVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartAudioClipPathVector(builder, numElems)
def AddVoiceHash(builder, VoiceHash): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(VoiceHash), 0)
def AudioAnimatorExcelAddVoiceHash(builder, VoiceHash):
    """This method is deprecated. Please switch to AddVoiceHash."""
    return AddVoiceHash(builder, VoiceHash)
def StartVoiceHashVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def AudioAnimatorExcelStartVoiceHashVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartVoiceHashVector(builder, numElems)
def End(builder): return builder.EndObject()
def AudioAnimatorExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)