# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BGMUIExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BGMUIExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBGMUIExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BGMUIExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BGMUIExcel
    def UIPrefab(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # BGMUIExcel
    def BGMId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def BGMUIExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddUIPrefab(builder, UIPrefab): builder.PrependUint32Slot(0, UIPrefab, 0)
def BGMUIExcelAddUIPrefab(builder, UIPrefab):
    """This method is deprecated. Please switch to AddUIPrefab."""
    return AddUIPrefab(builder, UIPrefab)
def AddBGMId(builder, BGMId): builder.PrependInt64Slot(1, BGMId, 0)
def BGMUIExcelAddBGMId(builder, BGMId):
    """This method is deprecated. Please switch to AddBGMId."""
    return AddBGMId(builder, BGMId)
def End(builder): return builder.EndObject()
def BGMUIExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)