# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CharacterWeaponExpBonusExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CharacterWeaponExpBonusExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCharacterWeaponExpBonusExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CharacterWeaponExpBonusExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CharacterWeaponExpBonusExcel
    def WeaponType_(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterWeaponExpBonusExcel
    def WeaponExpGrowthA(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterWeaponExpBonusExcel
    def WeaponExpGrowthB(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterWeaponExpBonusExcel
    def WeaponExpGrowthC(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # CharacterWeaponExpBonusExcel
    def WeaponExpGrowthZ(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(5)
def CharacterWeaponExpBonusExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddWeaponType_(builder, WeaponType_): builder.PrependInt32Slot(0, WeaponType_, 0)
def CharacterWeaponExpBonusExcelAddWeaponType_(builder, WeaponType_):
    """This method is deprecated. Please switch to AddWeaponType_."""
    return AddWeaponType_(builder, WeaponType_)
def AddWeaponExpGrowthA(builder, WeaponExpGrowthA): builder.PrependInt32Slot(1, WeaponExpGrowthA, 0)
def CharacterWeaponExpBonusExcelAddWeaponExpGrowthA(builder, WeaponExpGrowthA):
    """This method is deprecated. Please switch to AddWeaponExpGrowthA."""
    return AddWeaponExpGrowthA(builder, WeaponExpGrowthA)
def AddWeaponExpGrowthB(builder, WeaponExpGrowthB): builder.PrependInt32Slot(2, WeaponExpGrowthB, 0)
def CharacterWeaponExpBonusExcelAddWeaponExpGrowthB(builder, WeaponExpGrowthB):
    """This method is deprecated. Please switch to AddWeaponExpGrowthB."""
    return AddWeaponExpGrowthB(builder, WeaponExpGrowthB)
def AddWeaponExpGrowthC(builder, WeaponExpGrowthC): builder.PrependInt32Slot(3, WeaponExpGrowthC, 0)
def CharacterWeaponExpBonusExcelAddWeaponExpGrowthC(builder, WeaponExpGrowthC):
    """This method is deprecated. Please switch to AddWeaponExpGrowthC."""
    return AddWeaponExpGrowthC(builder, WeaponExpGrowthC)
def AddWeaponExpGrowthZ(builder, WeaponExpGrowthZ): builder.PrependInt32Slot(4, WeaponExpGrowthZ, 0)
def CharacterWeaponExpBonusExcelAddWeaponExpGrowthZ(builder, WeaponExpGrowthZ):
    """This method is deprecated. Please switch to AddWeaponExpGrowthZ."""
    return AddWeaponExpGrowthZ(builder, WeaponExpGrowthZ)
def End(builder): return builder.EndObject()
def CharacterWeaponExpBonusExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)