# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ContentsScenarioExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContentsScenarioExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContentsScenarioExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ContentsScenarioExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContentsScenarioExcel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentsScenarioExcel
    def LocalizeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ContentsScenarioExcel
    def ScenarioContentType_(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ContentsScenarioExcel
    def ScenarioGroupId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ContentsScenarioExcel
    def ScenarioGroupIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # ContentsScenarioExcel
    def ScenarioGroupIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ContentsScenarioExcel
    def ScenarioGroupIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def Start(builder): builder.StartObject(4)
def ContentsScenarioExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddId(builder, Id): builder.PrependUint32Slot(0, Id, 0)
def ContentsScenarioExcelAddId(builder, Id):
    """This method is deprecated. Please switch to AddId."""
    return AddId(builder, Id)
def AddLocalizeId(builder, LocalizeId): builder.PrependUint32Slot(1, LocalizeId, 0)
def ContentsScenarioExcelAddLocalizeId(builder, LocalizeId):
    """This method is deprecated. Please switch to AddLocalizeId."""
    return AddLocalizeId(builder, LocalizeId)
def AddScenarioContentType_(builder, ScenarioContentType_): builder.PrependInt32Slot(2, ScenarioContentType_, 0)
def ContentsScenarioExcelAddScenarioContentType_(builder, ScenarioContentType_):
    """This method is deprecated. Please switch to AddScenarioContentType_."""
    return AddScenarioContentType_(builder, ScenarioContentType_)
def AddScenarioGroupId(builder, ScenarioGroupId): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(ScenarioGroupId), 0)
def ContentsScenarioExcelAddScenarioGroupId(builder, ScenarioGroupId):
    """This method is deprecated. Please switch to AddScenarioGroupId."""
    return AddScenarioGroupId(builder, ScenarioGroupId)
def StartScenarioGroupIdVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def ContentsScenarioExcelStartScenarioGroupIdVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartScenarioGroupIdVector(builder, numElems)
def End(builder): return builder.EndObject()
def ContentsScenarioExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)