# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class Difficulty(object):
    Normal = 0
    Hard = 1
    VeryHard = 2
    Hardcore = 3
    Extreme = 4
    Insane = 5

