# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentBuffExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentBuffExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventContentBuffExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventContentBuffExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentBuffExcel
    def EventContentBuffId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffExcel
    def IsBuff(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EventContentBuffExcel
    def CharacterTag(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffExcel
    def SkillGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffExcel
    def IconPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffExcel
    def SpriteName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffExcel
    def BuffDescriptionLocalizeCodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffExcel
    def BuffDescriptionIconPath(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(8)
def EventContentBuffExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddEventContentBuffId(builder, EventContentBuffId): builder.PrependInt64Slot(0, EventContentBuffId, 0)
def EventContentBuffExcelAddEventContentBuffId(builder, EventContentBuffId):
    """This method is deprecated. Please switch to AddEventContentBuffId."""
    return AddEventContentBuffId(builder, EventContentBuffId)
def AddIsBuff(builder, IsBuff): builder.PrependBoolSlot(1, IsBuff, 0)
def EventContentBuffExcelAddIsBuff(builder, IsBuff):
    """This method is deprecated. Please switch to AddIsBuff."""
    return AddIsBuff(builder, IsBuff)
def AddCharacterTag(builder, CharacterTag): builder.PrependInt32Slot(2, CharacterTag, 0)
def EventContentBuffExcelAddCharacterTag(builder, CharacterTag):
    """This method is deprecated. Please switch to AddCharacterTag."""
    return AddCharacterTag(builder, CharacterTag)
def AddSkillGroupId(builder, SkillGroupId): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(SkillGroupId), 0)
def EventContentBuffExcelAddSkillGroupId(builder, SkillGroupId):
    """This method is deprecated. Please switch to AddSkillGroupId."""
    return AddSkillGroupId(builder, SkillGroupId)
def AddIconPath(builder, IconPath): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(IconPath), 0)
def EventContentBuffExcelAddIconPath(builder, IconPath):
    """This method is deprecated. Please switch to AddIconPath."""
    return AddIconPath(builder, IconPath)
def AddSpriteName(builder, SpriteName): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(SpriteName), 0)
def EventContentBuffExcelAddSpriteName(builder, SpriteName):
    """This method is deprecated. Please switch to AddSpriteName."""
    return AddSpriteName(builder, SpriteName)
def AddBuffDescriptionLocalizeCodeId(builder, BuffDescriptionLocalizeCodeId): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(BuffDescriptionLocalizeCodeId), 0)
def EventContentBuffExcelAddBuffDescriptionLocalizeCodeId(builder, BuffDescriptionLocalizeCodeId):
    """This method is deprecated. Please switch to AddBuffDescriptionLocalizeCodeId."""
    return AddBuffDescriptionLocalizeCodeId(builder, BuffDescriptionLocalizeCodeId)
def AddBuffDescriptionIconPath(builder, BuffDescriptionIconPath): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(BuffDescriptionIconPath), 0)
def EventContentBuffExcelAddBuffDescriptionIconPath(builder, BuffDescriptionIconPath):
    """This method is deprecated. Please switch to AddBuffDescriptionIconPath."""
    return AddBuffDescriptionIconPath(builder, BuffDescriptionIconPath)
def End(builder): return builder.EndObject()
def EventContentBuffExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)