# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventContentBuffGroupExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventContentBuffGroupExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventContentBuffGroupExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventContentBuffGroupExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventContentBuffGroupExcel
    def EventContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffGroupExcel
    def BuffContentId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffGroupExcel
    def BuffGroupId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffGroupExcel
    def BuffGroupNameLocalizeCodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffGroupExcel
    def EventContentBuffId1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffGroupExcel
    def BuffNameLocalizeCodeId1(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffGroupExcel
    def EventContentBuffId2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffGroupExcel
    def BuffNameLocalizeCodeId2(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffGroupExcel
    def EventContentDebuffId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # EventContentBuffGroupExcel
    def DebuffNameLocalizeCodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EventContentBuffGroupExcel
    def BuffGroupProb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(11)
def EventContentBuffGroupExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddEventContentId(builder, EventContentId): builder.PrependInt64Slot(0, EventContentId, 0)
def EventContentBuffGroupExcelAddEventContentId(builder, EventContentId):
    """This method is deprecated. Please switch to AddEventContentId."""
    return AddEventContentId(builder, EventContentId)
def AddBuffContentId(builder, BuffContentId): builder.PrependInt64Slot(1, BuffContentId, 0)
def EventContentBuffGroupExcelAddBuffContentId(builder, BuffContentId):
    """This method is deprecated. Please switch to AddBuffContentId."""
    return AddBuffContentId(builder, BuffContentId)
def AddBuffGroupId(builder, BuffGroupId): builder.PrependInt64Slot(2, BuffGroupId, 0)
def EventContentBuffGroupExcelAddBuffGroupId(builder, BuffGroupId):
    """This method is deprecated. Please switch to AddBuffGroupId."""
    return AddBuffGroupId(builder, BuffGroupId)
def AddBuffGroupNameLocalizeCodeId(builder, BuffGroupNameLocalizeCodeId): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(BuffGroupNameLocalizeCodeId), 0)
def EventContentBuffGroupExcelAddBuffGroupNameLocalizeCodeId(builder, BuffGroupNameLocalizeCodeId):
    """This method is deprecated. Please switch to AddBuffGroupNameLocalizeCodeId."""
    return AddBuffGroupNameLocalizeCodeId(builder, BuffGroupNameLocalizeCodeId)
def AddEventContentBuffId1(builder, EventContentBuffId1): builder.PrependInt64Slot(4, EventContentBuffId1, 0)
def EventContentBuffGroupExcelAddEventContentBuffId1(builder, EventContentBuffId1):
    """This method is deprecated. Please switch to AddEventContentBuffId1."""
    return AddEventContentBuffId1(builder, EventContentBuffId1)
def AddBuffNameLocalizeCodeId1(builder, BuffNameLocalizeCodeId1): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(BuffNameLocalizeCodeId1), 0)
def EventContentBuffGroupExcelAddBuffNameLocalizeCodeId1(builder, BuffNameLocalizeCodeId1):
    """This method is deprecated. Please switch to AddBuffNameLocalizeCodeId1."""
    return AddBuffNameLocalizeCodeId1(builder, BuffNameLocalizeCodeId1)
def AddEventContentBuffId2(builder, EventContentBuffId2): builder.PrependInt64Slot(6, EventContentBuffId2, 0)
def EventContentBuffGroupExcelAddEventContentBuffId2(builder, EventContentBuffId2):
    """This method is deprecated. Please switch to AddEventContentBuffId2."""
    return AddEventContentBuffId2(builder, EventContentBuffId2)
def AddBuffNameLocalizeCodeId2(builder, BuffNameLocalizeCodeId2): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(BuffNameLocalizeCodeId2), 0)
def EventContentBuffGroupExcelAddBuffNameLocalizeCodeId2(builder, BuffNameLocalizeCodeId2):
    """This method is deprecated. Please switch to AddBuffNameLocalizeCodeId2."""
    return AddBuffNameLocalizeCodeId2(builder, BuffNameLocalizeCodeId2)
def AddEventContentDebuffId(builder, EventContentDebuffId): builder.PrependInt64Slot(8, EventContentDebuffId, 0)
def EventContentBuffGroupExcelAddEventContentDebuffId(builder, EventContentDebuffId):
    """This method is deprecated. Please switch to AddEventContentDebuffId."""
    return AddEventContentDebuffId(builder, EventContentDebuffId)
def AddDebuffNameLocalizeCodeId(builder, DebuffNameLocalizeCodeId): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(DebuffNameLocalizeCodeId), 0)
def EventContentBuffGroupExcelAddDebuffNameLocalizeCodeId(builder, DebuffNameLocalizeCodeId):
    """This method is deprecated. Please switch to AddDebuffNameLocalizeCodeId."""
    return AddDebuffNameLocalizeCodeId(builder, DebuffNameLocalizeCodeId)
def AddBuffGroupProb(builder, BuffGroupProb): builder.PrependInt64Slot(10, BuffGroupProb, 0)
def EventContentBuffGroupExcelAddBuffGroupProb(builder, BuffGroupProb):
    """This method is deprecated. Please switch to AddBuffGroupProb."""
    return AddBuffGroupProb(builder, BuffGroupProb)
def End(builder): return builder.EndObject()
def EventContentBuffGroupExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)