# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KatakanaConvertExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KatakanaConvertExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKatakanaConvertExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KatakanaConvertExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KatakanaConvertExcel
    def Kr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # KatakanaConvertExcel
    def Jp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def KatakanaConvertExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddKr(builder, Kr): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(Kr), 0)
def KatakanaConvertExcelAddKr(builder, Kr):
    """This method is deprecated. Please switch to AddKr."""
    return AddKr(builder, Kr)
def AddJp(builder, Jp): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Jp), 0)
def KatakanaConvertExcelAddJp(builder, Jp):
    """This method is deprecated. Please switch to AddJp."""
    return AddJp(builder, Jp)
def End(builder): return builder.EndObject()
def KatakanaConvertExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)