# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class KnockbackDirection(object):
    TargetToCaster = 0
    CasterToTarget = 1
    TargetToHitPosition = 2
    HitPositionToTarget = 3
    CasterToHitPosition = 4
    HitPositionToCaster = 5

