# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LocalizeSkillExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LocalizeSkillExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLocalizeSkillExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LocalizeSkillExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LocalizeSkillExcel
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LocalizeSkillExcel
    def NameKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeKr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def NameJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeJp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def NameTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeTh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def NameTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeTw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def NameEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(32))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeEn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(34))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def NameDe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(36))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionDe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(38))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeDe(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(40))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def NameFr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(42))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def DescriptionFr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(44))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizeSkillExcel
    def SkillInvokeLocalizeFr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(46))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(22)
def LocalizeSkillExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddKey(builder, Key): builder.PrependUint32Slot(0, Key, 0)
def LocalizeSkillExcelAddKey(builder, Key):
    """This method is deprecated. Please switch to AddKey."""
    return AddKey(builder, Key)
def AddNameKr(builder, NameKr): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(NameKr), 0)
def LocalizeSkillExcelAddNameKr(builder, NameKr):
    """This method is deprecated. Please switch to AddNameKr."""
    return AddNameKr(builder, NameKr)
def AddDescriptionKr(builder, DescriptionKr): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionKr), 0)
def LocalizeSkillExcelAddDescriptionKr(builder, DescriptionKr):
    """This method is deprecated. Please switch to AddDescriptionKr."""
    return AddDescriptionKr(builder, DescriptionKr)
def AddSkillInvokeLocalizeKr(builder, SkillInvokeLocalizeKr): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeKr), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeKr(builder, SkillInvokeLocalizeKr):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeKr."""
    return AddSkillInvokeLocalizeKr(builder, SkillInvokeLocalizeKr)
def AddNameJp(builder, NameJp): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(NameJp), 0)
def LocalizeSkillExcelAddNameJp(builder, NameJp):
    """This method is deprecated. Please switch to AddNameJp."""
    return AddNameJp(builder, NameJp)
def AddDescriptionJp(builder, DescriptionJp): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionJp), 0)
def LocalizeSkillExcelAddDescriptionJp(builder, DescriptionJp):
    """This method is deprecated. Please switch to AddDescriptionJp."""
    return AddDescriptionJp(builder, DescriptionJp)
def AddSkillInvokeLocalizeJp(builder, SkillInvokeLocalizeJp): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeJp), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeJp(builder, SkillInvokeLocalizeJp):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeJp."""
    return AddSkillInvokeLocalizeJp(builder, SkillInvokeLocalizeJp)
def AddNameTh(builder, NameTh): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(NameTh), 0)
def LocalizeSkillExcelAddNameTh(builder, NameTh):
    """This method is deprecated. Please switch to AddNameTh."""
    return AddNameTh(builder, NameTh)
def AddDescriptionTh(builder, DescriptionTh): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionTh), 0)
def LocalizeSkillExcelAddDescriptionTh(builder, DescriptionTh):
    """This method is deprecated. Please switch to AddDescriptionTh."""
    return AddDescriptionTh(builder, DescriptionTh)
def AddSkillInvokeLocalizeTh(builder, SkillInvokeLocalizeTh): builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeTh), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeTh(builder, SkillInvokeLocalizeTh):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeTh."""
    return AddSkillInvokeLocalizeTh(builder, SkillInvokeLocalizeTh)
def AddNameTw(builder, NameTw): builder.PrependUOffsetTRelativeSlot(10, flatbuffers.number_types.UOffsetTFlags.py_type(NameTw), 0)
def LocalizeSkillExcelAddNameTw(builder, NameTw):
    """This method is deprecated. Please switch to AddNameTw."""
    return AddNameTw(builder, NameTw)
def AddDescriptionTw(builder, DescriptionTw): builder.PrependUOffsetTRelativeSlot(11, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionTw), 0)
def LocalizeSkillExcelAddDescriptionTw(builder, DescriptionTw):
    """This method is deprecated. Please switch to AddDescriptionTw."""
    return AddDescriptionTw(builder, DescriptionTw)
def AddSkillInvokeLocalizeTw(builder, SkillInvokeLocalizeTw): builder.PrependUOffsetTRelativeSlot(12, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeTw), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeTw(builder, SkillInvokeLocalizeTw):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeTw."""
    return AddSkillInvokeLocalizeTw(builder, SkillInvokeLocalizeTw)
def AddNameEn(builder, NameEn): builder.PrependUOffsetTRelativeSlot(13, flatbuffers.number_types.UOffsetTFlags.py_type(NameEn), 0)
def LocalizeSkillExcelAddNameEn(builder, NameEn):
    """This method is deprecated. Please switch to AddNameEn."""
    return AddNameEn(builder, NameEn)
def AddDescriptionEn(builder, DescriptionEn): builder.PrependUOffsetTRelativeSlot(14, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionEn), 0)
def LocalizeSkillExcelAddDescriptionEn(builder, DescriptionEn):
    """This method is deprecated. Please switch to AddDescriptionEn."""
    return AddDescriptionEn(builder, DescriptionEn)
def AddSkillInvokeLocalizeEn(builder, SkillInvokeLocalizeEn): builder.PrependUOffsetTRelativeSlot(15, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeEn), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeEn(builder, SkillInvokeLocalizeEn):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeEn."""
    return AddSkillInvokeLocalizeEn(builder, SkillInvokeLocalizeEn)
def AddNameDe(builder, NameDe): builder.PrependUOffsetTRelativeSlot(16, flatbuffers.number_types.UOffsetTFlags.py_type(NameDe), 0)
def LocalizeSkillExcelAddNameDe(builder, NameDe):
    """This method is deprecated. Please switch to AddNameDe."""
    return AddNameDe(builder, NameDe)
def AddDescriptionDe(builder, DescriptionDe): builder.PrependUOffsetTRelativeSlot(17, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionDe), 0)
def LocalizeSkillExcelAddDescriptionDe(builder, DescriptionDe):
    """This method is deprecated. Please switch to AddDescriptionDe."""
    return AddDescriptionDe(builder, DescriptionDe)
def AddSkillInvokeLocalizeDe(builder, SkillInvokeLocalizeDe): builder.PrependUOffsetTRelativeSlot(18, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeDe), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeDe(builder, SkillInvokeLocalizeDe):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeDe."""
    return AddSkillInvokeLocalizeDe(builder, SkillInvokeLocalizeDe)
def AddNameFr(builder, NameFr): builder.PrependUOffsetTRelativeSlot(19, flatbuffers.number_types.UOffsetTFlags.py_type(NameFr), 0)
def LocalizeSkillExcelAddNameFr(builder, NameFr):
    """This method is deprecated. Please switch to AddNameFr."""
    return AddNameFr(builder, NameFr)
def AddDescriptionFr(builder, DescriptionFr): builder.PrependUOffsetTRelativeSlot(20, flatbuffers.number_types.UOffsetTFlags.py_type(DescriptionFr), 0)
def LocalizeSkillExcelAddDescriptionFr(builder, DescriptionFr):
    """This method is deprecated. Please switch to AddDescriptionFr."""
    return AddDescriptionFr(builder, DescriptionFr)
def AddSkillInvokeLocalizeFr(builder, SkillInvokeLocalizeFr): builder.PrependUOffsetTRelativeSlot(21, flatbuffers.number_types.UOffsetTFlags.py_type(SkillInvokeLocalizeFr), 0)
def LocalizeSkillExcelAddSkillInvokeLocalizeFr(builder, SkillInvokeLocalizeFr):
    """This method is deprecated. Please switch to AddSkillInvokeLocalizeFr."""
    return AddSkillInvokeLocalizeFr(builder, SkillInvokeLocalizeFr)
def End(builder): return builder.EndObject()
def LocalizeSkillExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)