# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LocalizePrefabExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LocalizePrefabExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLocalizePrefabExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LocalizePrefabExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LocalizePrefabExcel
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # LocalizePrefabExcel
    def Kr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizePrefabExcel
    def Jp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizePrefabExcel
    def Th(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizePrefabExcel
    def Tw(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizePrefabExcel
    def En(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizePrefabExcel
    def De(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # LocalizePrefabExcel
    def Fr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(8)
def LocalizePrefabExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddKey(builder, Key): builder.PrependUint32Slot(0, Key, 0)
def LocalizePrefabExcelAddKey(builder, Key):
    """This method is deprecated. Please switch to AddKey."""
    return AddKey(builder, Key)
def AddKr(builder, Kr): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Kr), 0)
def LocalizePrefabExcelAddKr(builder, Kr):
    """This method is deprecated. Please switch to AddKr."""
    return AddKr(builder, Kr)
def AddJp(builder, Jp): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(Jp), 0)
def LocalizePrefabExcelAddJp(builder, Jp):
    """This method is deprecated. Please switch to AddJp."""
    return AddJp(builder, Jp)
def AddTh(builder, Th): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(Th), 0)
def LocalizePrefabExcelAddTh(builder, Th):
    """This method is deprecated. Please switch to AddTh."""
    return AddTh(builder, Th)
def AddTw(builder, Tw): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(Tw), 0)
def LocalizePrefabExcelAddTw(builder, Tw):
    """This method is deprecated. Please switch to AddTw."""
    return AddTw(builder, Tw)
def AddEn(builder, En): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(En), 0)
def LocalizePrefabExcelAddEn(builder, En):
    """This method is deprecated. Please switch to AddEn."""
    return AddEn(builder, En)
def AddDe(builder, De): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(De), 0)
def LocalizePrefabExcelAddDe(builder, De):
    """This method is deprecated. Please switch to AddDe."""
    return AddDe(builder, De)
def AddFr(builder, Fr): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(Fr), 0)
def LocalizePrefabExcelAddFr(builder, Fr):
    """This method is deprecated. Please switch to AddFr."""
    return AddFr(builder, Fr)
def End(builder): return builder.EndObject()
def LocalizePrefabExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)