# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class LogicEffectCategory(object):
    None_ = 0
    Attack = 1
    Heal = 2
    Buff = 3
    Debuff = 4
    CrowdControl = 5
    Boss = 6
    Dummy = 7

