# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RaidStageSeasonRewardExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RaidStageSeasonRewardExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRaidStageSeasonRewardExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RaidStageSeasonRewardExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RaidStageSeasonRewardExcel
    def SeasonRewardId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelTypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelTypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelTypeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueId(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueIdAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueIdLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueIdIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueName(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueNameLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardParcelUniqueNameIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardAmount(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardAmountAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardAmountLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # RaidStageSeasonRewardExcel
    def SeasonRewardAmountIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def Start(builder): builder.StartObject(5)
def RaidStageSeasonRewardExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddSeasonRewardId(builder, SeasonRewardId): builder.PrependInt64Slot(0, SeasonRewardId, 0)
def RaidStageSeasonRewardExcelAddSeasonRewardId(builder, SeasonRewardId):
    """This method is deprecated. Please switch to AddSeasonRewardId."""
    return AddSeasonRewardId(builder, SeasonRewardId)
def AddSeasonRewardParcelType(builder, SeasonRewardParcelType): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(SeasonRewardParcelType), 0)
def RaidStageSeasonRewardExcelAddSeasonRewardParcelType(builder, SeasonRewardParcelType):
    """This method is deprecated. Please switch to AddSeasonRewardParcelType."""
    return AddSeasonRewardParcelType(builder, SeasonRewardParcelType)
def StartSeasonRewardParcelTypeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def RaidStageSeasonRewardExcelStartSeasonRewardParcelTypeVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartSeasonRewardParcelTypeVector(builder, numElems)
def AddSeasonRewardParcelUniqueId(builder, SeasonRewardParcelUniqueId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(SeasonRewardParcelUniqueId), 0)
def RaidStageSeasonRewardExcelAddSeasonRewardParcelUniqueId(builder, SeasonRewardParcelUniqueId):
    """This method is deprecated. Please switch to AddSeasonRewardParcelUniqueId."""
    return AddSeasonRewardParcelUniqueId(builder, SeasonRewardParcelUniqueId)
def StartSeasonRewardParcelUniqueIdVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def RaidStageSeasonRewardExcelStartSeasonRewardParcelUniqueIdVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartSeasonRewardParcelUniqueIdVector(builder, numElems)
def AddSeasonRewardParcelUniqueName(builder, SeasonRewardParcelUniqueName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(SeasonRewardParcelUniqueName), 0)
def RaidStageSeasonRewardExcelAddSeasonRewardParcelUniqueName(builder, SeasonRewardParcelUniqueName):
    """This method is deprecated. Please switch to AddSeasonRewardParcelUniqueName."""
    return AddSeasonRewardParcelUniqueName(builder, SeasonRewardParcelUniqueName)
def StartSeasonRewardParcelUniqueNameVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def RaidStageSeasonRewardExcelStartSeasonRewardParcelUniqueNameVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartSeasonRewardParcelUniqueNameVector(builder, numElems)
def AddSeasonRewardAmount(builder, SeasonRewardAmount): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(SeasonRewardAmount), 0)
def RaidStageSeasonRewardExcelAddSeasonRewardAmount(builder, SeasonRewardAmount):
    """This method is deprecated. Please switch to AddSeasonRewardAmount."""
    return AddSeasonRewardAmount(builder, SeasonRewardAmount)
def StartSeasonRewardAmountVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def RaidStageSeasonRewardExcelStartSeasonRewardAmountVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartSeasonRewardAmountVector(builder, numElems)
def End(builder): return builder.EndObject()
def RaidStageSeasonRewardExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)