# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class ScenarioCharacterAction(object):
    Idle = 0
    Shake = 1
    Greeting = 2
    FalldownLeft = 3
    FalldownRight = 4
    Stiff = 5
    Hophop = 6
    Jump = 7

