# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class ScenarioContentType(object):
    Prologue = 0
    WeekDungeon = 1
    Raid = 2
    Arena = 3
    Favor = 4
    Shop = 5
    EventContent = 6
    Craft = 7
    Chaser = 8

