# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScenarioTransitionExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScenarioTransitionExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScenarioTransitionExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScenarioTransitionExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScenarioTransitionExcel
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioTransitionExcel
    def TransitionOut(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioTransitionExcel
    def TransitionOutDuration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioTransitionExcel
    def TransitionOutResource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioTransitionExcel
    def TransitionIn(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioTransitionExcel
    def TransitionInDuration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioTransitionExcel
    def TransitionInResource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(7)
def ScenarioTransitionExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, Name): builder.PrependUint32Slot(0, Name, 0)
def ScenarioTransitionExcelAddName(builder, Name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, Name)
def AddTransitionOut(builder, TransitionOut): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(TransitionOut), 0)
def ScenarioTransitionExcelAddTransitionOut(builder, TransitionOut):
    """This method is deprecated. Please switch to AddTransitionOut."""
    return AddTransitionOut(builder, TransitionOut)
def AddTransitionOutDuration(builder, TransitionOutDuration): builder.PrependInt64Slot(2, TransitionOutDuration, 0)
def ScenarioTransitionExcelAddTransitionOutDuration(builder, TransitionOutDuration):
    """This method is deprecated. Please switch to AddTransitionOutDuration."""
    return AddTransitionOutDuration(builder, TransitionOutDuration)
def AddTransitionOutResource(builder, TransitionOutResource): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(TransitionOutResource), 0)
def ScenarioTransitionExcelAddTransitionOutResource(builder, TransitionOutResource):
    """This method is deprecated. Please switch to AddTransitionOutResource."""
    return AddTransitionOutResource(builder, TransitionOutResource)
def AddTransitionIn(builder, TransitionIn): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(TransitionIn), 0)
def ScenarioTransitionExcelAddTransitionIn(builder, TransitionIn):
    """This method is deprecated. Please switch to AddTransitionIn."""
    return AddTransitionIn(builder, TransitionIn)
def AddTransitionInDuration(builder, TransitionInDuration): builder.PrependInt64Slot(5, TransitionInDuration, 0)
def ScenarioTransitionExcelAddTransitionInDuration(builder, TransitionInDuration):
    """This method is deprecated. Please switch to AddTransitionInDuration."""
    return AddTransitionInDuration(builder, TransitionInDuration)
def AddTransitionInResource(builder, TransitionInResource): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(TransitionInResource), 0)
def ScenarioTransitionExcelAddTransitionInResource(builder, TransitionInResource):
    """This method is deprecated. Please switch to AddTransitionInResource."""
    return AddTransitionInResource(builder, TransitionInResource)
def End(builder): return builder.EndObject()
def ScenarioTransitionExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)