# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScenarioBGEffectExcel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScenarioBGEffectExcel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScenarioBGEffectExcel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScenarioBGEffectExcel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScenarioBGEffectExcel
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ScenarioBGEffectExcel
    def Effect(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ScenarioBGEffectExcel
    def Scroll(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ScenarioBGEffectExcel
    def ScrollTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioBGEffectExcel
    def ScrollFrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # ScenarioBGEffectExcel
    def ScrollTo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(6)
def ScenarioBGEffectExcelStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, Name): builder.PrependUint32Slot(0, Name, 0)
def ScenarioBGEffectExcelAddName(builder, Name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, Name)
def AddEffect(builder, Effect): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Effect), 0)
def ScenarioBGEffectExcelAddEffect(builder, Effect):
    """This method is deprecated. Please switch to AddEffect."""
    return AddEffect(builder, Effect)
def AddScroll(builder, Scroll): builder.PrependInt32Slot(2, Scroll, 0)
def ScenarioBGEffectExcelAddScroll(builder, Scroll):
    """This method is deprecated. Please switch to AddScroll."""
    return AddScroll(builder, Scroll)
def AddScrollTime(builder, ScrollTime): builder.PrependInt64Slot(3, ScrollTime, 0)
def ScenarioBGEffectExcelAddScrollTime(builder, ScrollTime):
    """This method is deprecated. Please switch to AddScrollTime."""
    return AddScrollTime(builder, ScrollTime)
def AddScrollFrom(builder, ScrollFrom): builder.PrependInt64Slot(4, ScrollFrom, 0)
def ScenarioBGEffectExcelAddScrollFrom(builder, ScrollFrom):
    """This method is deprecated. Please switch to AddScrollFrom."""
    return AddScrollFrom(builder, ScrollFrom)
def AddScrollTo(builder, ScrollTo): builder.PrependInt64Slot(5, ScrollTo, 0)
def ScenarioBGEffectExcelAddScrollTo(builder, ScrollTo):
    """This method is deprecated. Please switch to AddScrollTo."""
    return AddScrollTo(builder, ScrollTo)
def End(builder): return builder.EndObject()
def ScenarioBGEffectExcelEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)