# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class TacticRole(object):
    DamageDealer = 0
    Tanker = 1
    Supporter = 2
    Healer = 3
    Vehicle = 4

