# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class TargetingUnitType(object):
    None_ = 0
    Near = 1
    Far = 2
    MinHp = 3
    MaxHp = 4
    Random = 5

