# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class UnitType(object):
    None_ = 0
    AR = 1
    RF = 2
    HG = 3
    MG = 4
    SMG = 5
    SG = 6
    HZ = 7
    Melee = 8

