# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class WeekDay(object):
    Sunday = 0
    Monday = 1
    Tuesday = 2
    Wednesday = 3
    Thursday = 4
    Friday = 5
    Saturday = 6
    All = 7

