# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatData

class WeekDungeonType(object):
    None_ = 0
    ChaserA = 1
    ChaserB = 2
    ChaserC = 3
    FindGift = 4
    Blood = 5

